root: true
parserOptions:
  parser: babel-eslint
  sourceType: module
  ecmaVersion: 8
env:
  browser: true
  node: true
extends:
  - standard
  - prettier
  - prettier/vue
  - prettier/standard
  - plugin:vue/base
  - plugin:vue/essential
  - plugin:vue/recommended
  - plugin:vue/strongly-recommended
globals:
  __static: true
plugins:
  - prettier
rules:
  prettier/prettier:
    - 1
    - usePrettierrc: true
  # enable semicolons instead of ASI
  semi:
    - 1
    - always
  # disable console log
  no-console: 1
  # enforce consistent indentation
  vue/html-indent:
    - 2
    - tab
  vue/max-attributes-per-line: 0
  vue/html-self-closing: 0
