steps:
  - script: |
      echo Name
      echo $(Build.Repository.Name)
      echo Source Version
      echo $(Build.SourceVersion)
      echo Artifact Staging Directory
      echo $(Build.ArtifactStagingDirectory)/*
      echo Build id
      echo $(Build.BuildId)

  - task: GitHubRelease@0
    displayName: "Create GitHub Release"
    inputs:
      gitHubConnection: thermal
      repositoryName: $(Build.Repository.Name)
      action: "create"
      # Required when action == Create || Action == Edit
      target: $(Build.SourceVersion)
      # Required when action == Create
      # Options: auto, manual
      tagSource: "auto"
      assets: $(Build.ArtifactStagingDirectory)/*
      isDraft: true
      addChangeLog: true
