steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      echo Installing packages
      yarn
      echo Start building linux application
      yarn build:linux
      echo Linux build is complete
    displayName: "Build Linux app"

  - script: |
      cd dist
      ls
    displayName: "Validate build"

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)/dist"
      contents: |
        *.deb
        *.snap
        *.zip
        *.AppImage
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: "Copying files"

  - task: PublishPipelineArtifact@0
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: linux
    displayName: "Publish pipeline artifact"
